services:
  client:
    image: tireni/emartapp-client
    build:
      context: ./client
    ports:
      - 4200:4200
    container_name: client
    depends_on:
      - api
      - webapi
    networks:
      - emartapp-network

  api:
    image: tireni/emartapp-webapi
    build:
      context: ./nodeapi
    ports:
      - 5000:5000
    restart: always
    container_name: api
    depends_on:
      - nginx
      - emongo
    networks:
      - emartapp-network

  webapi:
    image: tireni/emartapp-api
    build:
      context: ./javaapi
    ports:
      - 9000:9000
    restart: always
    container_name: webapi
    depends_on:
      - emartdb
    networks:
      - emartapp-network

  nginx:
    restart: always
    image: nginx:alpine-slim
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - emartapp-network

  emongo:
    image: mongo:4.4.8-focal
    container_name: emongo
    environment:
      MONGO_INITDB_DATABASE: ${emongo-db}
    ports:
      - 27017:27017
    volumes:
      - emongo-data:/data/db

  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${emartdb-password}
      MYSQL_DATABASE: ${emart-db}
    networks:
      - emartapp-network
    volumes:
      - emartdb-data:/var/lib/mysql

networks:
  emartapp-network:
    driver: bridge


volumes:
  emongo-data:
  emartdb-data: