apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emongo-pvc
  namespace: emartapp-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emartdb-pvc
  namespace: emartapp-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
