apiVersion: apps/v1
kind: Deployment
metadata:
  name: emongo
  namespace: emartapp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emongo
  template:
    metadata:
      labels:
        app: emongo
    spec:
      containers:
      - name: emongo
        image: mongo:4.4.8-focal
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        volumeMounts:
          - name: emongo-storage
            mountPath: /data/db       
        ports:
          - name: emongo-port 
            containerPort: 27017
        env:
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-cret
                key: MONGO_INITDB_DATABASE
      volumes:
        - name: emongo-storage
          persistentVolumeClaim: 
            claimName: emongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: emongo
  namespace: emartapp-ns
spec:
  selector:
    app: emongo
  ports:
  - port: 27017
    targetPort: emongo-port
    protocol: TCP
  type: ClusterIP