apiVersion: apps/v1
kind: Deployment
metadata:
  name: emartdb
  namespace: emartapp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emartdb
  template:
    metadata:
      labels:
        app: emartdb
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.33
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        volumeMounts:
          - name: emartdb-storage
            mountPath: /var/lib/mysql               
        ports:
          - name: emartdb-port 
            containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-cret
                key: MYSQL_DATABASE
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-cret
                key: MYSQL_ROOT_PASSWORD          
      volumes:
        - name: emartdb-storage
          persistentVolumeClaim: 
            claimName: emartdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: emartdb
  namespace: emartapp-ns
spec:
  selector:
    app: emartmysql
  ports:
  - port: 3306
    targetPort: emartdb-port
    protocol: TCP
  type: ClusterIP