apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: emartapp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emartnginx
  template:
    metadata:
      labels:
        app: emartnginx
    spec:
      containers:
      - name: emart-nginx
        image: nginx:alpine-slim
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - name: nginx-port
            containerPort: 80
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: emartapp-ns
spec:
  selector:
    app: emartnginx
  ports:
  - port: 80
    targetPort: nginx-port 
    protocol: TCP
  type: LoadBalancer