apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: emartnginx
  template:
    metadata:
      labels:
        app: emartnginx
    spec:
      containers:
      - name: emart-nginx
        image: nginx:alpine-slim
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: emartnginx-port
            containerPort: 80
      volumeMounts:
        - name: nginx-files
          mountPath: /etc/nginx/conf.d/default.conf
      volumes:
      - name: angular-static-files
        hostPath:
          path: ../nginx/default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: emartnginx
  ports:
  - port: 80
    targetPort: emart-nginx-port 
    protocol: TCP
  type: LoadBalancer